### ISSUE TITLE
Make it configurable whether changing the setting for a group triggers the reload of the page.

### ISSUE THREAD

**Issue by Starraider** [dmind-gmbh/extension-cookieman#107]
# Feature Request
For example, if you use the **Google Tag Manager** , instead of the "inject"-method, to control whether a code snippet should be inserted, it may still be necessary to reload the page if the user changes the settings for a group.

So it would be very useful if you could configure, whether the change of the settings of a specific group triggers the reload of the page.

Like this:
plugin.tx_cookieman.settings.groups.mygroup.triggerPageReload = 1

**Comment by jonaseberledmind** [comment]
From my experience GTM does not need a reload when inserted some time after page load.
Can you find any reference for that?

If you need that, you could have an `inject` like this maybe?

    if (Cookie.get('_some_gtm_cookie')  === undefined) {
      location.reload()
    }

I want to avoid "feature creep" for edge cases. But I am open of course if this really is needed.

**Comment by jonaseberledmind** [comment]
Starraider, does that work for your use case?

**Comment by jonaseberledmind** [comment]
@Starraider I would like your feedback on this one.

**Comment by almfisch** [comment]
Hi,
I made something like this to reload after save:

`$('#cookieman-modal .modal-footer .btn').click(function(event){
     location.reload();
 });`

**Comment by jonaseberledmind** [comment]
@almfisch yes, that works. You could put it in your `cookieman-theme.js` (into the `hide()` function, too)

If one needs reload for when a specific trackingObject is included one could use the checking for a specific cookie that I posted above.

I am closing this as I think it is doable quite well right now.
