### ISSUE TITLE
Typo3 7 Compatibility

### ISSUE THREAD

**Issue by p-view** [dmind-gmbh/extension-cookieman#108]
Hi, any Chance for this?

**Comment by jonaseberledmind** [comment]
We won't do this officially. Mainly because we would to have acceptance tests for it.
But it is really not too hard to do. I have a v1 at a client and I am not sure if I even had to change anything back then.

**Comment by jonaseberledmind** [comment]
Sorry, closing this as there will be no officially supported v7-compatible version. 

But try with a v8-compatible one - I doubt that there would be a lot to change. It probably would just run like that.

**Comment by p-view** [comment]
Thanks for your hint, but  it shows nothing.

**Comment by jonaseberledmind** [comment]
I don't understand. Can you please clarify?

**Comment by p-view** [comment]
when i install the 8-compatible version on a 7er System there is no Error in Front or Backend. But its do not create any Code on the Website.

**Comment by Juerg-E** [comment]
@p-view Have you found a solution yet? I'm working on that problem too. My system: TYPO3 7.6.4, PHP Version 5.6.36.
Solved: Errors at TypoScriptSettingsProcessor.php, "f:variable" at Popup.html / PopupLayout.html
Have problem with this error message: Class TYPO3\CMS\Fluid\ViewHelpers\Format\JsonViewHelper does not exist 
- {f:format.json(value:'{groups:settings.groups, trackingObjects:settings.trackingObjects}')}

**Comment by jonaseberledmind** [comment]
@Juerg-E I suggest to take the EXT:vhs JSON ViewHelper instead.
