### ISSUE TITLE
Just a typo in the language files

### ISSUE THREAD

**Issue by ax-ha** [dmind-gmbh/extension-cookieman#109]
Thanks a lot for this wonderful extension!
 I just found a little typo in the default language file

File: dmind-gmbh/extension-cookieman/blob/master/Resources/Private/Language/locallang.xlf
Line: 17
Id: introText
Property: source

> This website uses cookies. Those have two functions: On the one hand they are providing basic functionality for this website. On the other hand they allow us to improve our content for you by saving and analyzing anonymized user data. You can redraw your consent **to to** using these cookies at any time. Find more information regarding cookies on our %1$s and regarding us on the %2$s.

One of the "to"-words should be enough.
Please bear with me for not creating a pull request regarding this.

**Comment by jonaseberledmind** [comment]
Thank you for the feedback and for spotting this.
