### ISSUE TITLE
Option to hide CookieInfo-Table

### ISSUE THREAD

**Issue by almfisch** [dmind-gmbh/extension-cookieman#118]
Hi,
it would be nice to add a option for groups to hide the CookieInfoTable, so there would be no need to overwrite the default templates.

For example:

TS:

```
groups {
	OpenStreetMap {
		hideCookieInfos = 1
	}
}
```

Template (Popup.html):
```

<f:if condition="!{group.hideCookieInfos}">
	<div class="table-responsive">
	...
	</div>
</f:if>
```

Thank you and many regards
Andi

**Comment by jonaseberledmind** [comment]
I don't think we need a config option for that.

If the {settings.trackingObjects.{trackingObjectId}.show} is empty, no line for that tracking object will be shown. (https://docs.typo3.org/p/dmind/cookieman/2.4/en-us/Configuration/Reference/Index.html#trackingobjects-tracking-object-key-show)

We would just need to hide the table altogether if there are no rows to show ;) 

Would that work for you?

**Comment by jonaseberle** [comment]
@almfisch could you give us feedback if the changes would solve this issue? 
You can test them with `composer req dmind/cookieman:dev-master` / `dev-9lts` /  `dev-8lts`.

**Comment by almfisch** [comment]
Thank you and sorry for late respond. I think, that's a good solution.

**Comment by jonaseberledmind** [comment]
Great, thank you.
