### ISSUE TITLE
update js-cookie plugin to (at least) 2.2.1 or v3RC

### ISSUE THREAD

**Issue by medarob** [dmind-gmbh/extension-cookieman#124]
Not really a feature or bug, maybe an optimization:

I wanted to use the javascript library js-cookie myself and noticed it's already used by cookieman, so I don't need to include it twice.

When I compared the used versions I noticed that js-cookie v2.2.0 from the year 2017 is currently used in the extension. There is a newer version 2.2.1 available from 2019 and also a first release candidate for v3 from 2020.

I think an update to version 2.2.1 is a good option because there was the following fix:
 - Prevent XSS in the cookie attributes

Not sure if v3 will work out of the box with cookieman.

Link: https://github.com/js-cookie/js-cookie/releases

**Comment by jonaseberle** [comment]
Thank you for the notice.
Definitely a bug if the used version has a vulnerability.

Could you check if v3 would work by overwriting this:

**Comment by medarob** [comment]
I have overriden the js cookie javascript file with v3 as you have suggested and it seems to work. Both cookieman and my basic scenario.

Despite my tests I would suggest that you test it aswell, maybe you have more advanced settings in cookieman. But on first sight, it all looks good.

**Comment by jonaseberle** [comment]
I only updated to 2.2.1. If I read that correctly, 3.0 can only be loaded as module and we will support IE11 at least for this year. Also the API changed a bit and I was too lazy to check if that would affect us somewhere.
