### ISSUE TITLE
have Js/Injects/ folder

### ISSUE THREAD

**Issue by TrueType** [dmind-gmbh/extension-cookieman#131]
Injecting JS code by source script(s) is the prefered way to account for security policies. There is an example script in /Resources/Public/Js/example-inject.js

I suggest to create a folder /Resources/Public/Js/Injects as there may be many such inject scripts created. There is only one example in the extension and in an override structure in the site package extension may not be other script than inject scripts. But I would add it anyway.

**Comment by jonaseberle** [comment]
Applied in https://github.com/dmind-gmbh/extension-cookieman/commit/d34908cb3d30cc1c9d590e1c5c0266ceadd001cd
