### ISSUE TITLE
differentiate cookie language key strings

### ISSUE THREAD

**Issue by TrueType** [dmind-gmbh/extension-cookieman#133]
Hi,
Google Analytics and Mapbox both have the same cookie named "_ga". I cannot differentiate the description for these cookies.

**Comment by jonaseberle** [comment]
Hey Henri, you should use different keys and add its title and description as language key.

E.g. `myOtherTrackingItem` can have a translation `trackingobject.myOtherTrackingItem` as title and `trackingobject.myOtherTrackingItem.desc` as description.
(it is used here https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Private/Partials/TableRowsByGroup.html#L8)

If you want cookie removal for that cookie, add a `cookieRemovalPattern`  https://docs.typo3.org/p/dmind/cookieman/master/en-us/Configuration/Reference/Index.html#trackingobjects-tracking-object-key-show-tracking-item-key-htmlcookieremovalpattern

**Comment by jonaseberle** [comment]
@TrueType did that work for you?
