### ISSUE TITLE
Cookies.remove(itemKey) doesn't work

### ISSUE THREAD

**Issue by msollmann** [dmind-gmbh/extension-cookieman#137]
If a user allows all (or some categories of) cookies and then reduce it to only functional cookies again, the cookie deletion (e.g. _ga, _gid) via `Cookies.remove(itemKey)` in cookieman.js (line 289) doesn't work in Version 2.4.2/2.4.4 / TYPO3 9.5. The setting of new cookies is prevented as expected, only the existing but not allowed cookies remain.

I solved it by replacing this line by 
`document.cookie = itemKey + '=; Path=/; Domain=mydomain.de; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';`

Is it a bug, feature or misconfiguration?

**Comment by jonaseberle** [comment]
Hi @msollmann,

are these HTML cookies? 
Can you share the configuration for the tracking item? Is `htmlCookieRemovalPattern` involved?

This is the last change AFAIK in that area: https://github.com/dmind-gmbh/extension-cookieman/commit/26db500e8628ad3726adca21269ef2eb4584603a

I would not want `document.cookie` but rather stick with the [js-cookie library](https://github.com/js-cookie/js-cookie) (`Cookies.remove(...)`). 
Can you please try with that in your browser's JavaScript console?

Maybe we need to use `Cookies.remove('name', { path: '' })` or other parameters?

**Comment by Mainbird** [comment]
Hi @jonaseberle,

I got the same issue as @msollmann and replacing `Cookies.remove(itemKey)` with `Cookies.remove(itemKey, { path: '' })` did not work for me.

Some cookies like _gid, _ga, or _gcl_au were still present in this case, but 
`Cookies.remove(itemKey, { path: '', domain: '.' + document.location.host })` is working for me.

**Comment by jonaseberle** [comment]
That might be a specific with Google Cookies. I've seen it even that way:

    domain: www.xxx.yy
    cookie domain: .xxx.yy

Deleting `_gat` worked for me with these commands (all work on `/` as well as on a subpage `/subpage`):

    Cookies.remove('_gat', {domain: '.xxx.yy'})
    Cookies.remove('_gat', {path: '/', domain: '.xxx.yy'})
    Cookies.remove('_gat', {path: '', domain: '.xxx.yy'})

The path/domain settings of cookies are (to my knowledge) not readable in JavaScript so we will have to try several `Cookies.remove(...)`s.

So I suggest:
    fullDomain = document.location.host # www.xxx.yy
    secondLevelDomain = fullDomain.split('.').slice(1).join('.') # xxx.yy
    Cookies.remove(itemKey)
    Cookies.remove(itemKey, {path: ''})
    Cookies.remove(itemKey, {path: '', domain: fullDomain})
    Cookies.remove(itemKey, {path: '', domain: '.' + secondLevelDomain}))

What do you think?

**Comment by Mainbird** [comment]
Yeah, you are right it's not possible to get the metadata of a cookie. I think this solution is fair enough :).
