### ISSUE TITLE
Unknown namespace in Partials/TableRowsByGroup.html

### ISSUE THREAD

**Issue by PeaceSfiSh** [dmind-gmbh/extension-cookieman#147]
The error 'c' is a unknown namespace appeared while referencing the default Partial/TableRowsByGroup.html in an own Template, because the Dmind/Cookieman/ViewHelpers were used, but not referenced.

Please declare non global ViewHelpers where the are used.

**Comment by jonaseberle** [comment]
@PeaceSfiSh it is already fixed since https://github.com/dmind-gmbh/extension-cookieman/commit/ad0a9a75a9f1887884cfa8f907e4364f8e157f44 but we haven't made a new release yet.
