### ISSUE TITLE
Granular Consent

### ISSUE THREAD

**Issue by msollmann** [dmind-gmbh/extension-cookieman#149]
Hi guys,

are you planning a more granular consent for future versions? This would offer the choice of single providers (like google maps, google analytics, youtube ...) instead of categories.

Best regards
Michael

**Comment by jonaseberle** [comment]
We plan to stay with groups of consents. 
But it's your choice how you use the grouping. You can make a group "Youtube" or "Google Maps" with only a single TrackingObject. You can decide if you want to add something to the [show](https://docs.typo3.org/p/dmind/cookieman/master/en-us/Configuration/Reference/Index.html#trackingobjects-tracking-object-key-show) property - if you don't define anything there, the table of "cookies" (aka trackingObjects) won't be shown for that group.

**Comment by msollmann** [comment]
Unfortunately some of my clients (or their data protection officers) insist on a two-level-consent (category and provider). So I cannot use your awesome extension for all of my projects. Thank you anyway!

**Comment by jonaseberle** [comment]
Ok. I don't understand why it should not work but it's ok.

**Comment by msollmann** [comment]
If I understand you right, I can use the groups either for categories (like "statistics", "marketing"...) or for single providers like "Youtube" or "Google Maps" - but not for both (in a 2-level-way). This is not enough for some of my clients.

**Comment by jonaseberle** [comment]
No, you are completey free to define categories and put the wanted TrackingObjects into it.

You can make groups Youtube, marketing, essential, ...

**Comment by msollmann** [comment]
But not:

1) Statistics
  a) Google Analytics
2) Marketing
  a) YouTube
  b) Google Maps
  c) Google Ads
3) Essential
  a)....

With the possibility for the user to choose e.g. 1) Statistics + 2a) YouTube + 2c) Google Ads (as you ca see on https://de.borlabs.io/)

**Comment by jonaseberle** [comment]
That's just a frontend thing. But you are right, it is not that obvious out of the box and the default templates don't support that.
