### ISSUE TITLE
Save / Protocol User-Consent

### ISSUE THREAD

**Issue by almfisch** [dmind-gmbh/extension-cookieman#172]
Hi,

after a long conversation with an external 'data protection officer' (Datenschutzbeauftragter), he said that the user-consent must be saved in a protocol with timestamp and IP-Addresse, especially for US-Services like GoogleAnalytics and YouTube.
Is there a solution planned or is it better to build a own solution (database or file based)?

Regards from Bavaria
Andi

**Comment by jonaseberle** [comment]
Basically we don't agree with that judgement at all basically.
Maybe legislation changes and then we will reconsider the decision for sure.
So no, we won't have that feature.
