### ISSUE TITLE
Respect do-not-track-settings (navigator.doNotTrack)

### ISSUE THREAD

**Issue by jfax** [dmind-gmbh/extension-cookieman#177]
# Feature Request

**Basic**
Enabling respect-settings in TypoScript. When set "Respect Do-Not-Track-Settings in Browser", NO cookie-banner is shown when this user visits the website. Automatically all settings are set to minimal (only necessary). That means: No tracking, block all external content. 

**A user with DNT-settings will not see the same**
When I change my browser settings in this way, I am aware that I cannot see a lot of services. That can be fallback font if google-fonts are used, no re-captcha, no youtube-embedding, not google-maps (...). 

**Example youtube-video or google-maps**
Not sure how this in handled here, but cookie services sometimes replace embeddings like youtube-embed with an image and a message like "we need your approval...". When clicked on a blocked item, cookie-settings should popup. When checked for example "allow youtube" the youtube-film should start when closing the cookie-settings-box

**Benefit**
Experienced users with this settings can visit websites without being forced to click on a cookie-consent-tool.

**Comment by jonaseberle** [comment]
Sorry for the late reply - I unconsciously deactivated issue notifications for this repo.

Your question is a bit broad. Would you like to have something changed from the current behaviour or is it a general question how cookieman handles this right now?

**Comment by jonaseberle** [comment]
@jfax Here is what cookieman allows to do right now with Do-Not-Track https://docs.typo3.org/p/dmind/cookieman/master/en-us/search.html?q=dnt&check_keywords=yes&area=default

**Comment by jfax** [comment]
closed - should be ok with existing status quo
