### ISSUE TITLE
Document new example tracking objects 

### ISSUE THREAD

**Issue by jonaseberle** [dmind-gmbh/extension-cookieman#178]
Through https://github.com/dmind-gmbh/extension-cookieman/commit/c9763c470406796b0f701fcf980d2ceffc34cffd we received new example configurations for MicrosoftForms, MicrosoftStream, GoogleMaps, Youtube, SlideShare.

This should be documented here:

https://docs.typo3.org/p/dmind/cookieman/master/en-us/Configuration/Reference/Index.html#trackingobjects

**Comment by okroener** [comment]
@jonaseberle I am not sure whether the cookies are all correct, the scanner report from cookiebot finds different ones ... do you have any clue why this might happen?

**Comment by jonaseberle** [comment]
@okroener I don't know. 
If available I like to take the "official" vendor's data protection declaration or cookie list.
