### ISSUE TITLE
Cookie settings revoke button

### ISSUE THREAD

**Issue by okroener** [dmind-gmbh/extension-cookieman#179]
Other cookie manager provide a settings button fixed to the lower left, in order to show the settings dialogue.

I have currently made a prototype for the bootstrap 4 theme and the intention is to make this item configurable in  TypoScript.

What do you think about that feature?

**Comment by jonaseberle** [comment]
Sorry, I haven't seen that issue earlier. 
Honestly I don't think showing a floating settings button somewhere is a good UX-choice. 
We have the information about how to add a modal re-opener in the documentation and I like to include that in the footer menu or on the data protection page.
