### ISSUE TITLE
Support for Bootstrap 5

### ISSUE THREAD

**Issue by Schwamo** [dmind-gmbh/extension-cookieman#185]
# Feature Request

Currently the popup does not open when working with Bootstrap 5.
I think there are only a few adjustment in the JS necessary. Unfortunately I cannot do them on my own.
Support would be so great!

**Comment by bucheggerOnline** [comment]
yes. have the same issue and don't really know how to adjust it.

**Comment by jonaseberle** [comment]
We do not have a theme for Bootstrap 5, yet. Use a custom template https://docs.typo3.org/p/dmind/cookieman/master/en-us/Configuration/Customization/Index.html - I don't think it is too hard to adapt to Bootstrap 5.
Then, please by all means share it with us.

**Comment by zenoussi** [comment]
var cookieModal = new bootstrap.Modal(document.getElementById('cookieman-modal'));

cookieman.show = function() {
  cookieModal.show();
};

cookieman.hide = function() {
  cookieModal.hide();
};

**Comment by bucheggerOnline** [comment]
I just added a pull request with a complete bootstrap5 theme. ;)

**Comment by jonaseberle** [comment]
It is merged into master but will go into the other branches when I find time.
Ping me if you need a release for v8/v9/v10 urgently.
