### ISSUE TITLE
removeTrackingObjectItem() throws a warning because cookieName is undefined

### ISSUE THREAD

**Issue by Moongazer** [dmind-gmbh/extension-cookieman#206]
The following line gives the warning **'Cookie "undefined" has been rejected for invalid domain.'** on each click on any save button, because `removeDisabledTrackingObjects()` is always executed.
https://github.com/dmind-gmbh/extension-cookieman/blob/88c0b281d86563bb3d5d9ace450c873c2c4b3301/Resources/Public/Js/cookieman.js#L297
Clearly `cookieName` is not initialized in `else` case.

**Comment by jonaseberle** [comment]
Please give some more information:

Browser? Configuration?

**Comment by Moongazer** [comment]
Sorry, was digging a bit more and it seem this behavior is different depending on the environment. First of all: I'm using Firefox 86 on Ubuntu.

The message above occurs using a local DDEV (domain `https://projectname.ddev.site:81`). Because this environment should be very close to the online version in my opinion, I was sure it will occur there as well, but its slightly different: **'Cookie "undefined" will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite'** (js.cookie.min.js:98:3)

As configuration I used the example tracking-object "GoogleAnalytics". The messages are printed as soon as the "save" button is clicked, and if none of the configured cookies exists.

Its not a big issue as the script still seems to work, but I thought I will report it early to be future save.

**Comment by jonaseberle** [comment]
I suggest to ignore everything else and check why your cookie is called "undefined".

**Comment by jonaseberle** [comment]
@Moongazer any progress? Please show your config if the problem persists.

**Comment by Moongazer** [comment]
Haven't had time yet, but will test it again ASAP in a clean DDEV environment to reproduce it step by step.

**Comment by Moongazer** [comment]
Here are the steps to reproduce it:

1) Installed Cookieman through composer inside a clean TYPO3 v10.4.13 (I used DDEV)
2) Added Cookieman TS to root template
3) Added Cookieman example-config TS to root template  (no further configuration)
4) Reload page, wait for modal, click "Accept all cookies".

The browser console will show 14 times '_Cookie "undefined" has been rejected for invalid domain_' messages as well as '_Cookie "undefined" will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value..._'

Like I said earlier, the 'undefined' results IMO because the variable `cookieName` is not declared in the `else` case:
```
/* cookieman.js */

    function removeTrackingObjectItem(itemKey, oItem) {
        if (oItem.type === 'cookie_http+html') {
            if (Object.prototype.hasOwnProperty.call(oItem, 'htmlCookieRemovalPattern') && oItem['htmlCookieRemovalPattern'] !== '') {
                // ...
            } else {
                removeHtmlCookie(cookieName) // cookieName is never declared?!
            }
        }
    }
```

**Comment by jonaseberle** [comment]
Thank you. Now I understand. I haven't noticed before and we have that code for a long time already...
The `else` just needs to go.

**Comment by Moongazer** [comment]
Also sorry, I didn't recognize that `itemKey` is the cookie name, otherwise I'd have mentioned it at the beginning. Thanks anyway!
