### ISSUE TITLE
Translate duration and type

### ISSUE THREAD

**Issue by prathers** [dmind-gmbh/extension-cookieman#211]
I'm having trouble translating  the duration and type in a trackingobject.

I have this:
```
plugin.tx_cookieman._LOCAL_LANG {
    da {
        trackingobject.AADNonce.desc = Benyttes til implementering af Microsoft-forms på hjemmesiden.
    }
}
```
But I would like to have a translated duration and type as well (see attached)

![Hjem_-_Recompli](https://user-images.githubusercontent.com/3508890/114390900-1a631480-9b97-11eb-9854-ae93f54dede7.png)

I've tried with 
```
trackingobject.AADNonce.duration = session
trackingobject.AADNonce.type = HTTP
```
but no success

**Comment by jonaseberle** [comment]
Hi Preben,

I think what you want is this (HTTP-only cookie + lifetime=session):

```
trackingobject.AADNonce.duration = 
trackingobject.AADNonce.durationUnit = session
trackingobject.AADNonce.type = cookie_http
```

https://docs.typo3.org/p/dmind/cookieman/2.7/en-us/Configuration/Reference/Index.html#trackingobjects-tracking-object-key-show-tracking-item-key-type

https://docs.typo3.org/p/dmind/cookieman/2.7/en-us/Configuration/Reference/Index.html#trackingobjects-tracking-object-key-show-tracking-item-key-durationunit (we should add a hint here about how to use a custom one, too - it works just like `type`, just with the localization key `durationUnit.*`)

**Comment by prathers** [comment]
I've tried that too with same result unfortunately
![Recompli__TYPO3_CMS_10_4_14_](https://user-images.githubusercontent.com/3508890/114534772-a46eb400-9c4f-11eb-96ae-d1fd9fec4a82.png)

**Comment by jonaseberle** [comment]
My bad. It is 

```
trackingobject.AADNonce.show.yourTableRowName.duration = 
trackingobject.AADNonce.show.yourTableRowName.durationUnit = session
trackingobject.AADNonce.show.yourTableRowName.type = cookie_http
```

or (looks like MicrosoftForms):

https://github.com/dmind-gmbh/extension-cookieman/blob/master/Configuration/TypoScript/TrackingObjects/MicrosoftForms.typoscript

**Comment by prathers** [comment]
Worx!
Thanks a million
