### ISSUE TITLE
Site reloads immediately, if I try to open the cookie details

### ISSUE THREAD

**Issue by Treupo** [dmind-gmbh/extension-cookieman#222]
# Bug Report

## Prerequisites

* [Y] Can you reproduce the problem on TYPO3 v8.7 LTS
* [N] Can you reproduce the problem on TYPO3 v9.5 LTS
* [N] Can you reproduce the problem on TYPO3 v10.4 LTS
* [N] Can you reproduce the problem on TYPO3 master

## Description

[Description of the bug]

## Steps to Reproduce

1. Install Cookieman and include both templates, base template and examples.
2. Open frontend and wait untill cookiebanner is showing up
3. click on "settings" and then on one of the categories, for example "mandatory"

**Expected behavior:** 
I expected to see the list of cookies, which are in the list

**Actual behavior:** 
At the moment the list is showing for one second and then the page is reloading.
There is no error in the console.

## Versions
TYPO3 8.7.40
Cookieman 2.7.0

**Comment by jonaseberle** [comment]
Hi Philipp,
please check which click handlers registered on the element. In the default template that's just a Bootstrap collapse.
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1678001/120626438-f0c1bd80-c462-11eb-9c73-b6b9712cc9cb.png">
You can crosscheck here https://cookieman.d-mind.de/theme-bootstrap4-modal with the default templates. I can't reproduce that behaviour.

**Comment by Treupo** [comment]
Hello, thanks for the quick reply.

I had to switch [plugin.tx_cookieman.settings.theme] to bootstrap3-modal because I am using bootstrap 3. It was set to bootstrap4-modal as default.
Now it works.

Thanks.

**Comment by jonaseberle** [comment]
Great.
