### ISSUE TITLE
Question: How to inject on specific Page ID

### ISSUE THREAD

**Issue by phoenixh** [dmind-gmbh/extension-cookieman#223]
Hello there,

sorry to ask... but how is it possible to Combine the Clause for the Page UID 123 with the Inject Code?

    [page["uid"] == 123]
                page.headerData.100 = TEXT
                page.headerData.100. value (
                <script type="text/javascript">
                                alert('CONFIRMATION');
                                </script>                            
                )
    [global]

I only want the Script be called on a specific ID (Confirmation Page after submitting a Form)

Thank you and all the Best

**Comment by jonaseberle** [comment]
Hi @phoenixh,

yes, by using TYPO3's default functionality to have page-specific TypoScript (`[page["uid"] == 123]`, as you already wrote) you can configure cookieman differently for a certain page.

If you have something specific on that page you could also do it in JavaScript:
```JavaScript
trackingObjects {
  ...
    inject (
      <script>
        if (document.querySelector('#page_123')) {
          alert('on page 123')
        }
        if (document.querySelector('.youtube-vide')) {
          alert('this page has YT')
        }
      </script>
    )
  }
```

**Comment by phoenixh** [comment]
I will try that one - thank you @jonaseberle

**Comment by jonaseberle** [comment]
A very common one for a different configuration would be `[site("identifier") == "mysite"]`, of course ;)

**Comment by phoenixh** [comment]
But that won't work:
       inject (
            [page["uid"] == 754]
            page.headerData.100 = TEXT
            page.headerData.100. value (
            <script type="text/javascript">
                alert('CONFIRMATION');
            </script>                            
            )
            [global]
        )

**Comment by phoenixh** [comment]
And the Site (also the Others) won't print the Page Id in the <body /> Tag. So there is not way to do that by Javascript.
Is it possible to do that by Typoscript?

**Comment by jonaseberle** [comment]
No ;) That's not valid TypoScript syntax. Conditions can only be on the top level. Please see https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/TypoScriptSyntax/Syntax/TypoScriptSyntax.html#conditions-lines-starting-with

Also what is `page.headerData` doing inside the cookieman config? `inject` shall contain HTML that will be put on the page. Please see https://docs.typo3.org/p/dmind/cookieman/master/en-us/Configuration/Example/Index.html for an example.

**Comment by phoenixh** [comment]
@jonaseberle okay, got it now.
But that way I have to Duplicate the complete Cookie Definition for for Page != 123 and Page == 123.

So i just added:
```
    plugin.tx_cookieman.settings.trackingObjects {
        Ttd {
           inject (
               alert('CODE ONLY FOR PAGE 123');
           )
        }
    }
```
That seems to work now.

**Comment by jonaseberle** [comment]
You don't have to duplicate the whole definition. Just the part that you want to override:
```
plugin.tx_cookieman.settings.trackingObjects {
    Ttd {
       inject (
         <script>
           alert('everywhere')
         </script>
       )
    }
    show {
      some_cookie {
         duration = 13
         durationUnit = months
         type = cookie_http+html
         provider = My Website Inc.
       }
    }
}

[page["uid"] == 754]
  plugin.tx_cookieman.settings.trackingObjects.Ttd.inject (
    <script>
      alert('page 754')
    </script>
  )
[GLOBAL]
```

**Comment by phoenixh** [comment]
To overwrite the inject Array on a specific Page UID worked out well. 
Thank you @jonaseberle
