### ISSUE TITLE
difficolties out of the box ...

### ISSUE THREAD

**Issue by t3webman** [dmind-gmbh/extension-cookieman#227]
# Bug Report
I'm not that good in programming TYPO3 ... this is my issue:

website: http://site.argenti.ch/ (development at time of writing)
otherwise: https://argenti.ch/ (if I activated anyhow)

TYPO3 v10.4 LTS
jQuery v2.2.4
Bootstrap v3.3.7

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 master

## Description

 **without configuring anything** (I only extended the translations to have my own langage files since I work with italian as default, and then other 3) **with the example loaded** the popup comes up correctly for every language, I can click the settings but when I select a cookie category (let's say 'mandatory') the page gets reloaded ...

and if I where in another language than DEFAULT (italian), it will go back to DEFAULT

## Steps to Reproduce

1. access the site, click settings and then try to visualize cookie details

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Versions

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by t3webman** [comment]
So sorry ... a bit more 'fiddling' and I got quite a bit further:

`plugin.tx_cookieman.settings.theme = bootstrap3-modal` took care of a lot

I also got the configuration going, only that upon saving (use of one of the buttons in the modal) nothing happens and nothing is injected ...

of course will I continue to 'fiddle' and I might figure it out ... if so I'll report and close the 'bug'

again, sorry, this is probably not the place to have this beginners dialogue

**Comment by jonaseberle** [comment]
> again, sorry, this is probably not the place to have this beginners dialogue
All is fine :) We can switch to the TYPO3 Slack if you want.

If you included the example TrackingObjects
![image](https://user-images.githubusercontent.com/1678001/133564740-6867679d-f8ad-4572-8368-e2d84ab1b2bb.png)
you should see some messages in the JavaScript console when Cookieman loads the example TrackingObjects.

You can try it here https://cookieman.d-mind.de/theme-bootstrap3-modal
I set up that demo basically by just composer-installing cookieman and including the 2 TypoScripts.

**Comment by t3webman** [comment]
thanx jonas ... in the meantime did I contribute to complete italian 100% (because I needed it) :-)
(how does this get accepted, only 3% is)

I have all working, the only thing it doesn't do is take the script out when I revoke the cookies, I have to manually refresh the page for that ...

if I accept and save it does inject ... and I see this is the same in your demo (bootstrap3-modal) ... maybe a javascript refresh when the consent is withdrawn ... (otherwise I'll add a notification to refresh the page to stop the script if you revoke)

I'll let you close this 'bug-report' ...

**Comment by jonaseberle** [comment]
> thanx jonas ... in the meantime did I contribute to complete italian 100% (because I needed it) :-)
(how does this get accepted, only 3% is)

There are TYPO3 language managers on Crowdin that are going to accept it. If it does not happen in the next days, please ask in the TYPO3 Slack in [#cig-crowdin-localization](https://typo3.slack.com/archives/CMUG7C04F). I can also accept them, but I do not want to step on anyone's toes and I do not speak Italian ;)

> I have all working, the only thing it doesn't do is take the script out when I revoke the cookies, I have to manually refresh the page for that ...

Maybe it is a display bug in the browser console. There is nothing happening on page load regarding cookie removal - If they are gone after page load they were already gone when you clicked the "deny all" or "save" button.

Have you succeeded in configuring your needed tracking objects? If not, please ask (best in Slack) and I'll help you. You also helped the project with your translations :)
