### ISSUE TITLE
data-bs-backdrop="static" not working in bootstrap-5-theme

### ISSUE THREAD

**Issue by HenryAveMedi** [dmind-gmbh/extension-cookieman#232]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Cookieman modal is not accepting bootstrap modal attibutes, especifically "data-bs-backdrop" "data-bs-keyboard"

**Describe the solution you'd like**
change your cookiman theme javascript to read the backdrop from the template layout data-bs-backdrop
-I want to give it data-bs-backdrop="static" so the modal can't be close in any other way than clicking on the the cookie options

**Additional context**
https://getbootstrap.com/docs/5.0/components/modal/#static-backdrop

**Comment by jonaseberle** [comment]
Sorry, but we don't plan to do that.

Reasoning: In our understanding a consent banner needs to be closable without saving any consent. That is in our understanding a requirement thus the default templates should adhere to it.

You can adapt that in your custom theme though if you want.

There has also already been an issue about that: https://github.com/dmind-gmbh/extension-cookieman/issues/96 - it includes some pointers that we want to include in the documentation.
