### ISSUE TITLE
Minimize/compress plugin output

### ISSUE THREAD

**Issue by cundd** [dmind-gmbh/extension-cookieman#255]
# Feature Request

**Is your feature request related to a problem? Please describe.**
The extension creates a relatively large HTML table with a lot of whitespace in the source code. This could possibly made slimmer.

**Describe the solution you'd like**
Maybe the output could simply be wrapped inside `<f:spaceless>`.

**Describe alternatives you've considered**
This of course is also possible by using a custom layout file.

**Comment by jonaseberle** [comment]
You can use an HTML minifier in your site, like https://extensions.typo3.org/extension/min which works fine with cookieman.

If you want to make a pull request, I am of course fine with `f:spaceless`, too.

For the next major version we want to [load configuration and HTML via AJAX](https://github.com/dmind-gmbh/extension-cookieman/issues/201) anyways.

**Comment by cundd** [comment]
Oh, thats very interesting.

Would a PR with `f:spaceless` be still useful once the AJAX feature landed?

**Comment by jonaseberle** [comment]
Yes! :)

**Comment by jonaseberle** [comment]
We forgot to close here. ;)
