### ISSUE TITLE
Destroy cookie CookieConsent if is older than some specified date

### ISSUE THREAD

**Issue by agendartobias** [dmind-gmbh/extension-cookieman#265]
Hello,

does anyone know how can i destroy cookie CookieConsent if is older then some specified date?

On production i integrated new group of cookies and add some new cookie. Now i want that all users get new/updated cookieconsent promt so they can confirm new cookies that i added

**Comment by jonaseberle** [comment]
Unfortunately you can only give it a lifetime, but once set you do not know when it was set.

I think your use case is this https://github.com/dmind-gmbh/extension-cookieman/issues/182 (changing tracking objects should invalidate earlier consent).

**Comment by jonaseberle** [comment]
I'll close here. Feel free to reopen.
