### ISSUE TITLE
Why using void return in themes?

### ISSUE THREAD

**Issue by dkern** [dmind-gmbh/extension-cookieman#267]
This is neither a real bug, nor a feature. But something that makes no sense. Why is `cookieman.theme` always assigned an `undefined` in the examples? The IIFE is executed but without any return, the `cookieman.theme` will always be undefined.

https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Public/Themes/bootstrap5-modal/cookieman-theme.js#L3

What is the sense of this? This is also shown to me directly as an error in my IDE.

The notation is also unusual by the way. Normally an IIFE is not called directly behind the brackets, but outside. 
https://developer.mozilla.org/de/docs/Glossary/IIFE

```js
// cookieman
(function() {}())

// regular
(function() {})()

// or, as we're in 2022 ;)
(() => {})()
```

**Comment by jonaseberle** [comment]
Hi @dkern, thanks for the notice. 
We have never used `cookieman.theme` but I think we had in mind to do it once. So it has been forgotten there the assignment can go completely.

I was not aware that we were using a non-standard IIFE here and a PR is most welcome. Thanks!

Regarding `=>`: That should wait for cookieman v3 where we can go ES2019 IMHO.
We have put the [IE 11 support promise in the docs](https://docs.typo3.org/p/dmind/cookieman/main/en-us/Introduction/Index.html?highlight=internet%20explorer#compatibility).

We are planning to branch off v2 after working on some of the issues that should mostly go to v2, too.

**Comment by jonaseberle** [comment]
Would you like to do a PR for the IIFE issue?
