### ISSUE TITLE
Removal of cookies is not complete due to missing "/" path

### ISSUE THREAD

**Issue by svewap** [dmind-gmbh/extension-cookieman#270]
# Bug Report

## Prerequisites

* [ x ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ x ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ x ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ x ] Can you reproduce the problem on TYPO3 master

## Description

Under certain circumstances, the removal fails because the cookies are created with the path / and the remove command does not call it explicitly. Tested under Chrome.
My suggestion: Always call the / in a variant as well:

```
Cookies.remove(name, {path: ''})
Cookies.remove(name, {path: '/'})
Cookies.remove(name, {path: '', domain: fullDomain})
Cookies.remove(name, {path: '/', domain: fullDomain})
Cookies.remove(name, {path: '', domain: '.' + secondLevelDomain})
Cookies.remove(name, {path: '/', domain: '.' + secondLevelDomain})
```

**Comment by jonaseberle** [comment]
Thanks for the report. That sounds like a good idea.

https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Public/Js/cookieman.js#L349-L358
