### ISSUE TITLE
Add test if the modal window can be displayed

### ISSUE THREAD

**Issue by svewap** [dmind-gmbh/extension-cookieman#274]
Recently, the modal window is suppressed by the Firefox extension Ghostery. This can have unpleasant consequences. The backdrop layer is only displayed and the entire website is no longer usable. A check with a hint would therefore be useful.
example:
```
cookieman.show = function () {
    const cookiemanModal = $('#cookieman-modal');
    cookiemanModal.appendTo($('body'));
    const cookiemanEl = document.getElementById('cookieman-modal')
    modal = new bootstrap.Modal(
      cookiemanEl,
      {
        backdrop: showBackdrop
      }
    )
    cookiemanModal.on('shown.bs.modal', function (event) {
      if (cookiemanModal.css('display') == 'none') {
        modal.hide();
        cookieman.showSuppressionWarning();
      }
    })
    modal.show();
  }
  cookieman.hide = function () {
    modal && modal.hide()
  }
  cookieman.showSuppressionWarning = function () {
    $('<div />').addClass('suppression-warning').html($('#cookieman-suppression-warning').html()).css({display:'block',position:'fixed',bottom:0,left:0,right:0,'z-index': 88888,'background-color':'#d78484', color:'#000','text-align': 'center',padding:'7px','font-size': '1.2rem'}).appendTo($('body'));
}
```

**Comment by jonaseberle** [comment]
Hi Sven, 
please help me understand some questions I have about that.

Why does that Firefox extension block a standard modal? That sounds like a false positive that needs fixing in that extension, doesn't it?

Is it reproducible for example with the [Bootstrap 5 demo](https://getbootstrap.com/docs/5.2/components/modal/#live-demo)?
What about the other [cookieman default themes](https://cookieman.d-mind.de/) of cookieman? Which are affected?

I use Firefox, but I don't use that extension.

**Comment by svewap** [comment]
Hi Jonas,
the extension doesn't block standard modals by class, but by id #cookieman-modal. The default BS modal is still function, but it can be reproduced with your demo.

Here is a list, what it suppresses.
```
.small.cookie-consent, .clearfix > #cookies, .container ~ div[data-react-class="CookieAgree"], .container.cookieinfo, .container[data-js*="cookie-message"], .container > #cookie-law-info-bar, .w-100.cookie, .row[data-test-selector*="cookie-banner"], .active.cookie, .active.cookie-banner, .active.rgpd-modal, .active.GDPR, .active.disclaimer, .current.blocker.blocker-cookies.jquery-modal, .modal.sm_optin_bg, .modal.udc-bar-holder, .modal.udc-ovr, .card[id*="consent-bar"], .alert.ccpa-message, .alert.rgpd, .alert[data-behaviour="cookie-banner"], .alert[data-cookie="banner-cookie"], .alert[data-name="eu_biscuits"], .alert[data-ng-if="showCookieDisclaimer"], .alert[ng-hide*="ShowCookieInfo"], .alert[ng-if="cookieAlert"], .alert[ng-if="showCookieDisclaimer"], .alert[ng-show*="cookiePopup"], #page > #tenantAcceptText, #page > .privacy-optin, #header + #content > #left > #rlblock_left, #header ~ div[aria-label*="cookieconsent"], #content > #center > .dose > .dosesingle, #content > #right > .dose > .dosesingle, #content > #cookie, #footer > #cookieConsent, #footer > #cookies, #footer > .cookies, #footer > #cookie-law-info-bar, #cookieman-modal, a[href^="https://content.oneindia.com/www/delivery/"], a[href^="https://pussl"], [href*="postlnk.com"], [href*="passtechusa.com"], [href*="librateam.net"] {
  display: none !important;
}
```

It is therefore not a malfunction because this is intentional. From my point of view, it is legitimate to want to suppress the annoying cookie popups. Consequently, there must be a fallback to the "only allow necessary cookies" setting if the cookie popup is not displayed. Nevertheless, there must not be a malfunction. Possibly, the problem will still show up with other ad blockers in the future.

**Comment by jonaseberle** [comment]
In my opinion it is not legitmate to suppress consent.

Regarding such extensions:
If problems arise, people using an extension that implicitly change websites' HTML or code should be aware that disabling those extensions might fix problems on websites.
In this case I see they are injecting some custom hack into my website. Maybe I would care if I was behind the idea of that extension. But I am not.

You could work with them to educate them that they need to remove the backdrop as well. Our default themes use default Bootstrap so that shouldn't be too hard to understand.

It's always interesting to see what people are expecting from the web. 
By the way: I don't understand how your code would fix that.

**Comment by TrueType** [comment]
whoo. hard.

**Comment by svewap** [comment]
Because we offer opt in solutions, it should be legitimate to say no automatically.
To hide the backdrop automatically would not be technically possible because it is universal and used by other modals.
My solution restores usability by removing the backdrop again and giving a warning instead. You could also omit the warning and go into the default mode that only functional cookies are allowed.
Granted, the manipulation of the FF extension could be made more transparent. I still see it as a good service for the website visitor to keep the functionality and harden the cookieman script.

**Comment by jonaseberle** [comment]
Closing this. Please feel free to reopen.
