### ISSUE TITLE
EditorConfig sets wrong indent size

### ISSUE THREAD

**Issue by webian** [dmind-gmbh/extension-cookieman#291]
.editorconfig sets `indent_size = 2` for many file types where it should be 4.

**Comment by jonaseberle** [comment]
no.
It should be 2 (personal preference) ;)

**Comment by webian** [comment]
But the committed files are indented with 4 spaces.

**Comment by jonaseberle** [comment]
Feel free to send a PR

**Comment by webian** [comment]
Sure, can you reopen?

**Comment by webian** [comment]
Services.yaml has bot 2 and 4 space, what do you prefer?
