### ISSUE TITLE
Logo in modal header

### ISSUE THREAD

**Issue by webian** [dmind-gmbh/extension-cookieman#292]
# Feature Request

**Is your feature request related to a problem? Please describe.**
In small screen devices (smartphones), the modal popup easily covers the site logo. To maintain branding it would be useful to show the logo in the header of the modal.

I know that the popup appears after 2 seconds just to show the page first but in my opinion it is not enough and also this delay is annoying.

**Describe the solution you'd like**
Have the possibility to display the website logo in the modal header and set its dimensions via typoscript settings.

**Comment by jonaseberle** [comment]
This can be accepted if you send a Pull Request for it.

**Comment by jonaseberle** [comment]
I'll close here for now. It's easy to change the modal header in a Fluid template override. Please reopen if you think cookieman should support that natively.
