### ISSUE TITLE
Google Consent Mode Integration

### ISSUE THREAD

**Issue by mikeemike7** [dmind-gmbh/extension-cookieman#298]
Google Consent Mode Integration (Feature Request)

It would be nice (essential for comercial use) to have a tracking without consent.
When do you support google consent mode?
Greets from Münster, M.

**Comment by jonaseberle** [comment]
>  When do you support google consent mode?
Hmm, I don't know yet ;)

Maybe you can tell us a bit about what is required to support that and how cookieman could intgrate it.

**Comment by jonaseberle** [comment]
I'll close that for now. 
Please reopen if you still feel cookieman could support that natively.
