### ISSUE TITLE
add FAQ: Content-Security-Policy

### ISSUE THREAD

**Issue by jonaseberledmind** [dmind-gmbh/extension-cookieman#30]
# Feature Request

**Is your feature request related to a problem? Please describe.**
People that implement tracking solutions might implement CSP on their sites, too. As cookieman plays a role in including assets, it should be stated what that role is.

**Describe the solution you'd like**
We should have some words about CSP and cookieman in the manual.

**Comment by sebkln** [comment]
Assign me for this, too.

**Comment by jonaseberledmind** [comment]
Thank you!
