### ISSUE TITLE
split shipped TypoScript into Base + Examples

### ISSUE THREAD

**Issue by jonaseberledmind** [dmind-gmbh/extension-cookieman#31]
# Feature Request

**Is your feature request related to a problem? Please describe.**
It is not ideal that examples are mixed into the base setup.

**Describe the solution you'd like**
"Examples" should be a separate TypoScript-template that can be included optionally.

**Describe alternatives you've considered**
For the time being you could disable all shipped examples: 

     plugin.tx_cookieman.settings.trackingObjects >
     plugin.tx_cookieman.settings.groups >

**Comment by sebkln** [comment]
Great, you already split it up to make configuration easier!

I'd suggest to reinsert the `mandatory` group including the `CookieConsent` object, as `CookieConsent` is technically necessary and not an example.

This would also render a cookie group again in the popup, which better illustrates the functionality of this extension.

    plugin.tx_cookieman {
        settings {
            groups {
                mandatory {
                    preselected = 1
                    disabled = 1
                    trackingObjects {
                        0 = CookieConsent
                    }
                }
            }
        }
    }

**Comment by jonaseberledmind** [comment]
Very good idea!
