### ISSUE TITLE
Cookies get set on page refresh despite preferences

### ISSUE THREAD

**Issue by aarong-dev** [dmind-gmbh/extension-cookieman#312]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.5 LTS
* [ ] Can you reproduce the problem on TYPO3 master

## Description

When a user denies any optional cookies and then refreshes the page, there are some cookies that still get allowed through. I'd expect those cookies to remain blocked when a user revisits the page

## Steps to Reproduce

1. Go on to a site as a user that hasn't configured cookies yet
2. Deny all cookies
3. Refresh the page
4. Cookies get set regardless

**Expected behavior:** Cookie preferences should be retained, with cookies being blocked when revisiting the site

**Actual behavior:** Cookies get created regardless of preferences

## Versions

Cookieman 2.14.3

**Comment by jonaseberle** [comment]
I'll close here. If you can provide more information we can reopen.
