### ISSUE TITLE
Setting: Open with a time delay

### ISSUE THREAD

**Issue by ingeniumdesign** [dmind-gmbh/extension-cookieman#314]
I have a question, could you add a typoscript setting so that the time delay popup opens?

Because certain tools or Google Core Web Vitals cannot cope with the quick opening of pop-ups.

Thanks

**Comment by jonaseberle** [comment]
We have a 2000ms here
https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Public/Js/cookieman-init.js

That works quite well for fast pages with PageSpeed Insights for me.

You can also use a custom init with another timeout. Would that work for you?

**Comment by ingeniumdesign** [comment]
Thanks, how can I overwrite the value?

**Comment by jonaseberle** [comment]
That's integrator territory. Just load your own cookieman-init.js.

**Comment by ingeniumdesign** [comment]
Thanks, it works!
