### ISSUE TITLE
The numbered array of a cookie group needs a fixed order

### ISSUE THREAD

**Issue by sebkln** [dmind-gmbh/extension-cookieman#33]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS

## Description

The `trackingObjects` which are listed in a cookie group (e.g. "marketing") must be **consecutively numbered** from `0` upwards. If a group is not configured this way, the `inject` code will not be executed.

This issue will affect only cookie groups with wrong ordering, not all groups.

## Steps to Reproduce

1. Install the extension.
2. Add the static template.
3. Open the frontend and accept all cookies: you will get 4 example log entries in the browser console.
4. Open the extension's `setup.typoscript` and change `3 = Bing` to `4 = Bing`: the browser console will be empty on reload.
5. Add `2 = Matomo` to the `trackingObjects` of the _"mandatory"_ group: the Matomo log entry will show in the browser console again.

**Expected behavior:**

The common usage of numbered arrays in TypoScript are flexible (e.g. `page.10`, `page.20`, …). It would be easier for integrators to configure the cookie groups if the current behaviour was loosened.

## Versions

On TYPO3 v8.7 LTS: cookieman v2.2.1
On TYPO3 v9.5 LTS: cookieman v2.2.2

**Comment by jonaseberledmind** [comment]
I can confirm. Thank you!

When converted to JSON it becomes an Object if the keys are not numerical and sequential...
