### ISSUE TITLE
Condition parse error

### ISSUE THREAD

**Issue by ghermens** [dmind-gmbh/extension-cookieman#334]
Composer install with TYPO3 12.4.15 and Cookieman dev/12lts.

I see some lines like 

Fri, 17 May 2024 09:30:02 +0200 [ERROR] request="5d371e6ded9e9" component="TYPO3.CMS.Core.TypoScript.IncludeTree.Visitor.IncludeTreeConditionMatcherVisitor": Expression could not be parsed. - {"expression":"{$plugin.tx_cookieman.settings.minify} == '0'"}

in the log.

Quoting the constant in Configuration/TypoScript/setup.typoscript line 71 helps:

`['{$plugin.tx_cookieman.settings.minify}' == '0']`

**Comment by jonaseberle** [comment]
Thank you @ghermens!
