### ISSUE TITLE
Add reST documentation

### ISSUE THREAD

**Issue by sebkln** [dmind-gmbh/extension-cookieman#34]
A reStructuredText documentation on docs.typo3.org is the best way to introduce and explain the extension to users.

I will take care of this. The finished documentation will include the usual sections. The contents are taken from the current README file. I plan to extend it with a FAQ or Troubleshooting section; maybe in a later step.

**Comment by jonaseberledmind** [comment]
Gorgeous! Thank you :)

**Comment by sebkln** [comment]
The documentation (PR #40)  is built upon the example manual provided by the t3docs team. Also, some good practices were copied from EXT:news docs.

I added the contents of the README into the different sections. In order to match the other docs, I had to add or rewrite come content (see "Changes and additions").

The whole documentation was rendered successfully in a local environment.


# Changes and additions

- "Introduction" contains a new list of features.
- "Installation" was rephrased to match EXT:news docs (but all former information is still listed there).
- I changed some examples from `<a href="">` to `<button>`.
- I used the official TYPO3 data types in TypoScript Reference (e.g. boolean). The data types are linked to the TSref.
- Some wording was changed.


## Rendering on docs.typo3.org

In order to get the new documentation rendered on docs.typo3.org, the following requirements must be met:

- Documentation must be available in 'master' branch.
- The link to the "External Manual" on extensions.typo3.org must be removed.
- `composer.json` must be up to date.
- Set up the [GitHub webhook](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Webhook.html#webhook-github). This allows to automatically render every change on docs.typo3.org

The new documentation adds a "Edit me on GitHub" button which allows users to quickly send PRs. If you don't want this, it can be easily removed.


## reST & Sphinx How-To

You can find all necessary information about reStructuredText in the ["How To document"](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Index.html) section on docs.typo3.org. It also includes a handy [Cheat Sheet](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CheatSheet.html).


## Additional notes

"Configuration" main page only contains some text and a doctree. If you add a heading on this page, all sub pages of "Configuration" will be rendered as sub pages of this heading in the main navigation. That's just the way sphinx works. As a workaround, I added all sections as separate files.

"TypoScript reference" is rendered with definition lists. Using the old `table-row` markup (e.g. [TSref](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Page/Index.html)) [is no longer recommended](https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/57#issuecomment-507760777) for new docs.



## Next steps

When this basic documentation is implemented, we can extend it with a new "FAQ" section inside "Configuration", e.g.:

- How to add a new cookie group?
- How to add a new tracking object?
- What to consider with a Content Security Policy?

**Comment by sebkln** [comment]
Cool!

When the new documentation is available on docs.typo3.org and up-to-date, I'd recommend to reduce the `README.md` to the general information (means: no configuration). Then you don't have to maintain two docs.

**Comment by jonaseberledmind** [comment]
Thank you for preparing this so thoroughly and well-thought!

I added the web hook and confirmed that https://intercept.typo3.com/admin/docs/deployments received a ping.
The "external manual" from https://extensions.typo3.org is removed.

**Comment by jonaseberle** [comment]
I reduced README.md. I'll make issues for FAQ entries.
The documentation looks and reads so nice :)
