### ISSUE TITLE
how to translate trackingobject provider

### ISSUE THREAD

**Issue by medarob** [dmind-gmbh/extension-cookieman#340]
I wanted to translate the trackingobject provider name in another language but nothing has worked so far.

```
plugin.tx_cookieman {
    settings {
        trackingObjects {
            CookieConsent {
                show {
                    MyTitle {
                        duration = 30
                        durationUnit = days
                        type = cookie_http+html
                        provider = Website
                    }
                }
            }
        }
    }
    _LOCAL_LANG {
        fr {
            trackingobject.MyTitle.provider = Site web
        }
}
```

The code shows:
```
<f:if condition="{trackingItem.provider}">
    {f:translate(
    key: trackingItem.provider,
    default: trackingItem.provider
    )}
</f:if>
```

But also adding `trackingItem.provider` as a key to an xlf file to override the string didn't work.

Should one of those methodes work or am I doing something wrong?

**Comment by jonaseberle** [comment]
Hmm, I've never used that :) Looking at https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Private/Partials/TableRowsByGroup.html#L37 it is also inconsistent – it would have been better to use 
```
{f:translate(
  key: provider.{trackingItem.provider},
  default: 'missing translation: provider.{trackingItem.provider}
)}
```
Would you like to make a PR for that?

For the current templates, it should be
```
_LOCAL_LANG {
        fr {
            Website = Site web
        }
}
```

**Comment by medarob** [comment]
Thank you for the answer. I can add a PR with that change.

I just also noticed the following inconsistency:

The default value for `desc` also is different.

current:
default: 'missing translation: trackingobject.{trackingItemId}.desc'

others:
default: 'missing translation: duration.{trackingItem.durationUnit}'
default: 'missing translation: type.{trackingItem.type}'

**Should it be:**
default: 'missing translation: **desc**.{trackingItem.**desc**}'

?

**Comment by jonaseberle** [comment]
Hmm, I think that is ok.

You want to translate
`trackingobject.{trackingItemId}` and `trackingobject.{trackingItemId}.desc` 
for the tracking object, but you don't want to translate the others (including your case "Website") for each trackingItem separately.

But let's use
```
{f:translate(
  key: provider.{trackingItem.provider},
  default: trackingItem.provider
)}
```
in the default templates.
– that way it is not breaking and users will see their current value, but they can provide a translation.

**Comment by medarob** [comment]
ok, created a pull request with the change
https://github.com/dmind-gmbh/extension-cookieman/pull/341
