### ISSUE TITLE
TYPO3 v8 compatible version 2.2.4 uses new TypoScript import syntax

### ISSUE THREAD

**Issue by sebkln** [dmind-gmbh/extension-cookieman#36]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS

## Description

The TER download of EXT:cookiebot v2.2.4 includes the new import syntax for TypoScript in the file `Configuration/TypoScript/Example/setup.typoscript`:

    @import 'EXT:cookieman/Configuration/TypoScript/TrackingObjects/*.typoscript'

**I guess this import can be dropped completely,** as the TrackingObjects are already loaded from the default `setup.typoscript` (which also includes the general settings).

**Comment by jonaseberledmind** [comment]
Oh dear, that must have slipped in for v8. 
I'd like to only load those needed in the default setup by default. Will fix that together with #31
