### ISSUE TITLE
DoNoTrack message is only rendered once

### ISSUE THREAD

**Issue by sebkln** [dmind-gmbh/extension-cookieman#37]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS

## Description

If the TypoScript settings for `DoNotTrack` are added to more than one cookie group, the DNT message is only rendered in the first cookie group.

    respectDnt = 1
    showDntMessage = 1

## Steps to Reproduce

1. Install the extension.
2. Add the static template.
3. Add a new cookie group (and set some demo cookies):

```
plugin.tx_cookieman {
    settings {
        groups {
            mandatory {
                preselected = 1
                disabled = 1
                trackingObjects {
                    0 = CookieConsent
                    1 = fe_typo_user
                }
            }

            marketing {
                trackingObjects {
                    1 = GoogleAnalytics
                    2 = GoogleTagManager
                    3 = Bing
                }

                respectDnt = 1
                showDntMessage = 1
            }

            analytics {
                trackingObjects {
                    0 = Matomo
                }

                respectDnt = 1
                showDntMessage = 1
            }
        }
    }
}
```

**Result after step 3:** The DNT message is rendered only in "marketing".

4. Now remove the "marketing" group. New result: The DNT message is now rendered in "analytics".

----

**Expected behavior:**

The message should be rendered in each cookie group that respects the `DoNotTrack` option.

**Actual behavior:**

The message is only rendered once.

## Versions

- TYPO3 8.7.29
- cookieman 2.2.4

## Additional note

I haven't tested if this behaviour is limited to rendering the message, or if the `DoNotTrack` browser setting isn't respected for the other group, too.

**Comment by jonaseberledmind** [comment]
Sweet, nice find :) 

This only finds the find occurency:
https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Public/Js/cookieman.js#L90
