### ISSUE TITLE
No cookie list shown

### ISSUE THREAD

**Issue by badg0n** [dmind-gmbh/extension-cookieman#38]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 master

## Description

I setup a configuration but the div#cookieman-acco remains completely empty.

Is there something wrong in my setup or is there more to configure to make it work?

Using bootstrap from [https://extensions.typo3.org/extension/bootstrap_package](url).

This is my TSconfig:

    temp.tx_cookieman.settings.groups.mandatory < 
    plugin.tx_cookieman.settings.groups.mandatory

    plugin.tx_cookieman.settings {
      trackingObjects {
        # extend the existing configuration for 'Matomo'
        Matomo {
          inject (
    <script type="text/javascript">
      var _paq = window._paq || [];
      // require user consent before processing data
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="/xxx.xxx/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '1']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; 
    s.parentNode.insertBefore(g,s);
      })();
    </script>
          )
        }
      }

      # reset existing groups
      groups >
      groups {
        # copy of default group 'mandatory'
        mandatory < temp.tx_cookieman.settings.groups.mandatory
    
                mandatory {
                    preselected = 1
                    disabled = 1
                    trackingObjects {
                        0 = CookieConsent
                        1 = fe_typo_user
                    }
                }

                analytics {
                    trackingObjects {
                        0 = Matomo
                    }

                    respectDnt = 1
                    showDntMessage = 1
                }
            }
        }
    }

    plugin.tx_cookieman._LOCAL_LANG {
      en {
        trackingobject\.Matomo = You can translate the name, but you do not have to.
        trackingobject\.Matomo\.desc = My own tracking pixel does not really track you. It's just here to cheer you up.
        group\.mandatory = My group is my castle.
      }
      default < .en
    }

## Steps to Reproduce

1. Set TSconfig

**Expected behavior:** A list of the pre-configured cookies is displayed.

**Actual behavior:** No list of the pre-configured cookies is displayed.

## Versions

TYPO3 v.10.1.0
Cookieman v.2.2.3
Bootstrap Package v11.0.1

**Comment by jonaseberledmind** [comment]
I am not sure I can follow you. 

The necessary setup is TypoScript, not TSConfig.

In v2.2 we separated the base TypoScript from the examples. 
We forgot to reflect that change in the example TypoScript. I have corrected [README.md.](../blob/master/README.md)

Even your setup could have given you an example cookie list, but it is not even valid TypoScript:
![grafik](https://user-images.githubusercontent.com/10654488/69666855-3bec5a80-108d-11ea-8fb8-9480912878bf.png)
(You can check the TypoScript object browser to see such errors)

btw: you should update to the current cookieman version 2.3.x which fixes JavaScript inclusion.

I suggest you start from the beginning. If you just want to see an example, just include the TypoScript templates "Cookieman" and "Cookieman (Example...)" (see [Integration](../blob/master/README.md)).

**Comment by jonaseberledmind** [comment]
Did you manage to see the examples?

**Comment by badg0n** [comment]
Yes. Thanks for helping. Everything's running now.
I like the new documentation.
