### ISSUE TITLE
Fluid Integration / Plugins / UIkit Theme

### ISSUE THREAD

**Issue by cakebake** [dmind-gmbh/extension-cookieman#47]
# Feature Request

**Is your feature request related to a problem? Please describe.**

I would like to use plugins based on the setting in Cookieman (ePrivacy), which, for example, integrate a Google Maps map ([go_maps_ext](https://extensions.typo3.org/extension/go_maps_ext)). Conditions in my own fluid template, whether a code can be executed (based on the user preference) would also be great.

**Describe the solution you'd like**

Currently not yet clear. I would start a discussion here.

**Describe alternatives you've considered**

Currently not yet clear.

**Additional context**

Maybe Cookieman can help me with the task, or are there other approaches? Maybe it's not up to Cookieman?

In return, I can provide a theme for [UIkit](https://getuikit.com/) as part of my project. I really like the structure of Cookieman. Thank you for sharing in the community. I hope that it comes to a productive use.

**Comment by jonaseberledmind** [comment]
Hello Jens,

so you would like to load the Google Map based on a given consent?

Instead of the map, I would put a placeholder which could show "In order to load the map, click here to give consent to using Google Maps". Clicking it would open the cookie consent (`cookieman.show()`). 

Then I would define a tracking object and do the map initialization in its `inject` option. Initilization would mean to replace the placeholder with the actual map.

That would require to inhibit the initialization of the map which is, as far as I see, not possible in EXT:go_maps because you cannot disable script inclusion as it is hard-coded here https://github.com/mhirdes/go_maps_ext/blob/72e689bfc46c1f3a6b0308fc1a3c80c5e71438ec/Classes/Controller/MapController.php and not controlled via TypoScript. You would have to ask the author or do a fork for that.

**Comment by jonaseberledmind** [comment]
As for the UIkit theme. I am happy for a pull request but would like acceptance tests for it, too. That would mean it must be possible to set it up automatically. The current themes can be tested against the bootstrap_package. Is there a UIkit base package that works out of the box with our supported TYPO3 versions (8/9/10)?

**Comment by cakebake** [comment]
> so you would like to load the Google Map based on a given consent?

Yes.

> Instead of the map, I would put a placeholder which could show "In order to load the map, click here to give consent to using Google Maps". Clicking it would open the cookie consent (cookieman.show()).

I had that idea, too. Is for the user in any case the best solution.

> Then I would define a tracking object and do the map initialization in its inject option. Initilization would mean to replace the placeholder with the actual map. Thus when consent was already given, this placeholder would not be shown.

Ok.

> That would require to inhibit the initialization of the map which is, as far as I see, EDIT: possible by setting include_manually in its extension configuration.

Unfortunately, I did not understand the hint. `include_manually`? Would it be possible to have a content element "Cookieman" as a wrapper for other content elements (Content, Plugins, HTML-Code, ...)? If accepted by the user, the Content Elment is activated. That would also simplify the configuration.

> Is there a UIkit base package that works out of the box with our supported TYPO3 versions (8/9/10)?

Not worth mentioning after my research.

**Comment by jonaseberledmind** [comment]
Cookieman is not a plugin wrapper. It can only include HTML/JS

include_manually - I've seen that here:
https://github.com/mhirdes/go_maps_ext/blob/72e689bfc46c1f3a6b0308fc1a3c80c5e71438ec/Classes/Controller/MapController.php#L105

**Comment by cakebake** [comment]
> Cookieman is not a plugin wrapper. It can only include HTML/JS

I thought it might be a useful feature. As an all in one solution to the DSGVO / ePrivacy.

> include_manually - I've seen that here

Oh, thanks for the hint. I had not seen it in the documentation. I'll take a look at it to see if I can do anything with the techniques now available.

Is there a need for some of this to flow back into the "Cookieman" project?

**Comment by jonaseberledmind** [comment]
>    Cookieman is not a plugin wrapper. It can only include HTML/JS
>> I thought it might be a useful feature. As an all in one solution to the DSGVO / ePrivacy.

No, I think that is feature creep and I do not want to support it. With some frontend skills, it is well possible to achieve that with the available means.

**Comment by cakebake** [comment]
> With some frontend skills, it is well possible to achieve that with the available means.

At the current time - and in terms of my requirements - I think that's possible.

**Comment by jonaseberledmind** [comment]
Tell me if you hit problems. 

We always want to know how it is actually used.
