### ISSUE TITLE
add FAQ: how do I add a group / tracking object? 

### ISSUE THREAD

**Issue by jonaseberledmind** [dmind-gmbh/extension-cookieman#48]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Supplemental to the documentation, it would be nice to have a 1. 2. 3. manual for how to add a new group or tracking object.

**Describe the solution you'd like**
This could go to the FAQ section in the manual.

**Comment by sebkln** [comment]
I can start the FAQ section with answers to these questions.

**Comment by jonaseberledmind** [comment]
Thank you!

**Comment by sebkln** [comment]
As the content of the new section is now more of a *How-To*, I reconsidered its name.

**Comment by sebkln** [comment]
docs.typo3.org shows the 2.3.x version of the documentation by default. This branch is missing the last changes (How-To section, theme differences). Can you merge them into the branch?

**Comment by jonaseberledmind** [comment]
I moved the newest version tags to the newest commit of each branch and it looks ok.
The docs team in Slack helped with retriggering the build because bamboo showed an unrelated error on https://intercept.typo3.com/admin/docs/deployments 

So I learned that the version tags need to be reset when updating docs (without releasing a new extension version). Thanks for alerting!
