### ISSUE TITLE
shy entities in locallang files are processed differently with v.2.3.4

### ISSUE THREAD

**Issue by sebkln** [dmind-gmbh/extension-cookieman#49]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS

## Description

After upgrading the extension from v2.2.4 to v2.3.4, the `&shy;` entities in the translations files are rendered like this:

    Hin&amp;shy;weis zu Coo&amp;shy;kies

## Steps to Reproduce

1. Update extension
2. Remove any custom configurations and use second static template (demo)

## Versions

TYPO3 v8
cookieman v2.3.4

**Comment by jonaseberledmind** [comment]
Oh damn. I feared that after the new translations but didn't see that problem in my test system.
We'll quickly release a fix. A temporary workaround would be to take the translation files of an older version.

**Comment by jonaseberledmind** [comment]
Lol http://cookieman.d-mind.de/de/theme-bootstrap4-modal

**Comment by sebkln** [comment]
Yeah, not so shy anymore. ;)

**Comment by jonaseberledmind** [comment]
new versions are out.
