### ISSUE TITLE
delete cookies after consent revocation

### ISSUE THREAD

**Issue by jonaseberledmind** [dmind-gmbh/extension-cookieman#65]
# Feature Request
Some have the expectation that cookies are removed when the user revokes the consent. I've seen that in this review for example https://jweiland.net/know-how/internet/ueberblick-cookie-extensions-und-externe-dienstleister.html#c6980 (German).

Until here that was not something we considered necessary for a consent plugin like cookieman.

We've rather seen cookieman as something that allows getting user consent to using **tracking objects** in general (like pixels, local storage, HTTP-/HTML-, HTTP- cookies, ...) - not just **cookies**. We expect the current discussion evolving so much around cookies only to soon widen towards tracking techniques in general.

Cookieman allows that e.g. facebook posts or Google Analytics are not loaded without consent, but it does not clean any already set tracking objects. 

We could add the functionality to remove HTML-cookies or even local/session storage items when a consent is revoked. 

**We are interested to know what you think.** Do we need that? Or should we make more clear via the documentation that cookieman does not clean cookies? Or ...?

**Comment by sebkln** [comment]
In my opinion, the important part is to prevent tracking unless the user consents.

For example, Matomo provides an API to ask for consent. On first page load, the tracking code will still set some cookies (`_pk_id` und `_pk_ses`), but Matomo will not process any data until consent.

Personally, I don't have a problem with that approach. But as everyone talks about *those bad cookies*, the typical user without this background knowledge might think that he already gets tracked and the whole cookie consent is a sham. Then again, will the typical user check for set cookies in the browser?

So if it's possible to delete selected cookies based on changed user settings, it could be a useful feature. But I don't know if it's technically feasible without custom configurations for every tracking object.

Regarding the jweiland review, I already commented that EXT:cookieman works the same as EXT:sg_cookie_optin and EXT:om_cookie_manager (as for the opt-out and cookie removal). For this other extensions the text was revised, unfortunately not for your extension.

**Comment by jonaseberledmind** [comment]
I have added a rudimentary cookie removal. 

So far it takes the key of the `plugin.tx_cookieman.settings.trackingObjects.*.show` array and only acts if `type = cookie_http+html`.

This won't be enough to capture cookies like `_ga_--container-id--` - we will need a new setting key like `regexForRemoval = _ga_.*` for that to be useful.

Also I'd like to extend it to LocalStorage which is used extensively by eTracker.

**Comment by philippmaurer** [comment]
I really could need that feature and like the suggested solution. 
I can create a pull request for that if you would like.

I would provide the information to the frontend via a "data-cookieman-trackingobject-pattern" attribute in the trackingobject "tr" tag in the "TableRowsByGroup.html" partials. Like that the ppls who edited the Popup.html in their custom themes, but still render the partial, wont have to change a thing.

**Comment by jonaseberledmind** [comment]
Hi @philippmaurer the rudimentary cookie removal is in the newest release. It works for e.g. the Google Analytics `_ga` etc. cookies. 

You mean you are missing the regex pattern for HTML-cookies or the extension to LocalStorage?

I'd like to learn about your use case. Can you describe a bit?

**Comment by philippmaurer** [comment]
I am working with Matomo, which creates cookies with a pattern of "_(?:pk|mtm)_(?:id|ses|...).\d{2}.[a-z\d]+", but the rudimentary cookie removal feature just checks for cookies with the exact "_pk_id", "_pk_ses", ... name, which it can not find and therefore does not delete. (Testet with 2.3.10) This feature suggestion would fix that problem. (Which i solved with an extra script that i added to my themes js code.)

**Comment by jonaseberledmind** [comment]
Ok, so we would need the regex pattern for HTML cookies.

It would not have to be a HTML change, though. I suggest to do it like that:

[ ] add TypoScript setting `plugin.tx_cookieman.settings.trackingObjects.*.show.htmlCookieRemovalPattern`
[ ] adapt cookieman.JS
[ ] add doku

**Comment by philippmaurer** [comment]
I am not sure if it catches all cases to put the pattern as a direct child to the `show` attribute. Would it not be better to add a pattern to each individually specified cookie?
`plugin.tx_cookieman.settings.trackingObjects.*.show.*.htmlCookieRemovalPattern`

**Comment by jonaseberledmind** [comment]
The `show` is the individual cookie (e.g. `_ga`). Maybe you mean `tracking object` (e.g. `GoogleAnalytics`)?

**Comment by jonaseberledmind** [comment]
Let's maybe talk with examples :) Maybe we just misunderstand each other.

I am thinking about an API like that:
```
plugin.tx_cookieman.settings.trackingObjects {
    Matomo {
        inject (
            ...
        )
        show {
            _pk_id\.--someId {
                htmlCookieRemovalPattern = pk_id\..*
                # later also possible: localStorageRemovalPattern = pk_id\..*
                duration = 13
                durationUnit = months
                type = cookie_http+html
                provider = Matomo
            }
            ...
        }
    }
}
```

**Comment by philippmaurer** [comment]
Hey, yeah. It was just a misunderstanding. I will implement it like that and send a pull request, but i might not have enough time for it today.

**Comment by jonaseberledmind** [comment]
Thank you, that'll be great :)

**Comment by philippmaurer** [comment]
With the current implementation only those cookies get deleted that are set on the root page due to the js-cookies specifications of the `remove` method.
By providing the current path of the page and all subpages of the current path, we can delete cookies that are set on specific pages in the current scope as well.
Like this:

    var cookiePath = '',
        cookiePaths = window.location.pathname.split('/')
    while (cookiePaths.length > 0 && typeof Cookies.get(itemKey) !== 'undefined') {
        cookiePath = cookiePath + cookiePaths.shift() + '/'
        //tries all paths from root to current subpage
        Cookies.remove(itemKey, {path: cookiePath})
    }

This also deletes the root cookies which were not set with a specific path option.
Shall i implement that, too?

**Comment by philippmaurer** [comment]
And how should malformed patterns like `((\d+$` be handled?

-  I could add a validity check (by using it in pregmatch on a dummy string) in the TypoScriptSettingsProcessor and add an entry to the error log. 
- Or i could also figure out a way to call a validator on it, wich would be the cleaner approach.
- Or it could be done in another ticket and i would add a console message to the browser, so someone can find out by testing it in frontend.

The best solution would be a validator i think, eventhough its normally ment to check models. Or is there something else to validate typoscript options?

**Comment by philippmaurer** [comment]
Without the two mentioned points above the rest works fine right now.
If you are interested you can see it [in  my fork](https://github.com/philippmaurer/extension-cookieman/tree/delete-cookies)

**Comment by jonaseberledmind** [comment]
Hi @philippmaurer, thank you for your work!

**cookie paths**
Do you have an example where a tracking solutions put cookies with paths other than `/`? If there is a use case it would be great to have, although I am not fond of your example code yet. Let's open a new ticket to implement that.

**malformed patterns**
I would try to reduce overhead as much as possible. That would mean to trigger a `console.error` from JavaScript but nothing else. You have the try / catch in your code already so you get validation with 2 lines of code.

I'll add some remarks to https://github.com/philippmaurer/extension-cookieman/commit/30a42a3e4e36178382b325253863c01a03458f85

Thank you so much for picking that up! :)

**Comment by jonaseberledmind** [comment]
We would need a documentation update in the reference https://github.com/philippmaurer/extension-cookieman/blob/master/Documentation/Configuration/Reference/Index.rst#trackingobjectstracking-object-keyshowtracking-item-keytype for `trackingObjects.‹tracking-object-key›.show.‹tracking-item-key›.htmlCookieRemovalPattern`, too. I can take care of that.

**Comment by philippmaurer** [comment]
Hi @jonaseberledmind 

__cookie paths__ 
To be honest this ist just about some cookies i set on my page, because i use the same library on two subpages and it therefore stores its information on the subpage to prevent conflicts. A more common case i can think of is a WordPress Multisite subdirectories setup, but nowadays everyone should use subdomains anyways.

Though, i thought about some other special cases in which the current default cookie removal is not sufficient, for example with the Matomo consent feature, [which expects an API call with an `forgetConsentGiven` payload in order to stop tracking](https://developer.matomo.org/guides/tracking-javascript-guide#step-4-user-removes-consent). Instead of a regex pattern approach, a callback approach would be more sufficient for that. It might even be better generally in the long run to implement a callback approach instead of the regex pattern one... Or it could be an additional feature.

**Comment by jonaseberledmind** [comment]
**callback on un-consent**
That could be done in a similar fashion like the onScriptLoaded() event.

But I don't think we need it. If Matomo is not consented its JavaScript will not be loaded because the loading is managed by cookieman (via the `inject()`). Thus it will not be active. 

The documentation of tracking solutions often expect that you include the main .js always but call something else afterwards or set another cookie (like GA's `gaOptOut` atrocity) to disable it. Our approach is different - we really do not even include the tracking object at all if not consented.

**Comment by philippmaurer** [comment]
The points that still need work then are:
- [ ] documentation update in the reference
- [ ] Add frontend tests
- [ ] build new cookieman.min.js

I could write a frontend test based on the code for the other tests, eventhoug iam not familiar to your test framework. Could you see if they work then and build the new cookieman.min.js?

**Comment by jonaseberledmind** [comment]
@philippmaurer If the type is `cookie_http+html` could we make the `htmlCookieRemovalPattern` optional and fall back to the `itemKey` if none is given?

That would allow us to make it non-breaking with existing configuration.

**Comment by philippmaurer** [comment]
I believe that is how it is implemented in [my fork](https://github.com/philippmaurer/extension-cookieman/blob/delete-cookies/Resources/Public/Js/cookieman.js). I also tested it and it is only cosidered if the pattern is provided and is not an empty string. Otherwise it will delete the root cookies with the given itemKey name. 
(If a pattern is provided though and the itemKey name does not match it, it will not be deleted. But that is expected behavior in my opinion.)

If you are ok with the current status i would create a pull request.

**Comment by jonaseberledmind** [comment]
Ah, sorry, didn't look carefully. It is in there already. Yes, please :)

**Comment by jonaseberledmind** [comment]
Thank you @philippmaurer, I just tested it in master. Great!

[ ] Acceptance tests for the new feature

I'll close here as I won't find the time soon and this is basically ready to go. Anyways, it is on my list for the future. For the moment I'll also drop my feature request for LocalStorage-cleaning.

I'll do a new release latest next week.
