### ISSUE TITLE
Consent not showing in 8.7 LTS, TypeError: o is null 

### ISSUE THREAD

**Issue by deezin** [dmind-gmbh/extension-cookieman#81]
# Bug Report

## Prerequisites

* [X] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 master

## Description

The PopUp won't show, the following error is thrown in the browser's console

TypeError: o is null 
`o = document.querySelector('[data-cookieman-settings]'),`

## Steps to Reproduce

1. installed the latest version of the plugin
2. added the static template to the root template
3. added the necessary pids in the plugin configuration

**Expected behavior:** the popup should show

**Actual behavior:** it does not show and the js error above is thrown

## Versions

2.3

**Comment by jonaseberledmind** [comment]
Did you include the TypoScript configuration for tracking objects (or the example?)

![image](https://user-images.githubusercontent.com/10654488/72663540-20019700-39f4-11ea-8c5d-f9af72fd3799.png)

**Comment by jonaseberledmind** [comment]
Nevermind, I just checked in a plain TYPO3 v8 that the base TypoScript is absolutely enough. 

By default it would load the *bootstrap4-modal* theme which expects jQuery. Even without bootstrap or jQuery, you would see the HTML output.

**Comment by jonaseberledmind** [comment]
@deezin, could you give some feedback how it's going for you?

**Comment by deezin** [comment]
@jonaseberledmind, sorry for the late reply, I just checked it with a plain TYPO3v8 installation and it works flawlessly. I guess my installation is just messed up. Thanks anyway for the quick replies!
