### ISSUE TITLE
Iframe handling?

### ISSUE THREAD

**Issue by stigfaerch** [dmind-gmbh/extension-cookieman#84]
It would be nice if there were some kind of handling of iframes which uses cookies.
For example YouTube code like this:
```
<iframe width="420" height="315"
src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>
```

**Comment by jonaseberledmind** [comment]
Hi Stig,

1) User consent before loading content
if you want to gather user consent before including youtube-iframes, you could do that with a custom tracking object and some JavaScript in its `inject` configuration. 
I would add the iframes like this in the HTML (not tested, just as an idea):
    
    <iframe width="420" height="315"
      src="/myPlaceHolderImageForYoutube.jpg"
      onclick="alert('We need your consent to include content from Youtube.'); cookieman.show()"
      data-src="https://www.youtube.com/embed/tgbNymZ7vqY">
    </iframe>

And then transform it via the JavaScript from the `inject` configuration.

2) Cookie management
As Youtube will work on cookies from the youtube.com domain inside the iframe, we cannot delete them when consent is revoked.
PS: You can use the youtube-nocookie.com - domain to include videos which makes it presumably a bit easier with GDPR although I suggest to still not include them without user consent.

An easy solution I sometimes take is to load a preview image and upon clicking warn the user like 'To show this video, a connection with Youtube will be established - OK - Cancel' - this is close to the example above but would not use cookieman to manage the consent.

What type of youtube functionality would you expect or like to see from cookieman? Happy to hear from you.

**Comment by jonaseberledmind** [comment]
Hi Stig, how would you like this to be handled?
Would be happy to hear from you.

**Comment by jonaseberledmind** [comment]
@stigfaerch I want your feedback on this.

**Comment by almfisch** [comment]
Hi,
I did it that way:

Insert iFrame with data-src="xxx" instead of src="xxx".

I add CSS-Classes to my iFrames for different types, like YouTube oder GoogleMaps:
`class="iframe_yt" or class="iframe_gm"`

In a JS-File replace the iFrames, if no consent:
```
$('.iframe_yt').each(function(){
     $(this).replaceWith('<div class="iframe_ph iframe_ph_yt"><div class="iframe_ph_title">YouTube Placeholder</div></div>');
 });
```
And after consent:
```
$('.iframe_yt').each(function(){
     var src = $(this).data('src');
     $(this).attr('src', src);
});
```
Andi

**Comment by jonaseberledmind** [comment]
That sounds very practical to me.
Do you think there is something that cookieman should provide to make that easier?

**Comment by almfisch** [comment]
I think, it is easy enough. So everyone can write his own logic for diffrent types of iframes (YouTube, Vimeo, GoogleMaps...).

**Comment by jonaseberledmind** [comment]
Ok. Lets close this.
