### ISSUE TITLE
Preselected Options only work, if the option is disabled

### ISSUE THREAD

**Issue by philippmaurer** [dmind-gmbh/extension-cookieman#85]
# Bug Report

## Prerequisites
* [x] Can you reproduce the problem on TYPO3 master

## Description

If you set an optiongroup to preselected = 1 over TypoScript, but do not set it to disabled, the group is still unselected in the frontend.

## Steps to Reproduce

1. Set up cookieman and create a new group
2. set the new group as preselected
3. Load the frontend and see the error. The group is not selected.

**Expected behavior:**

The group should be preselected, if the group was not deselected earlier.

**Actual behavior:**

The group is deselected.

## Versions

Tested with 2.3.10, but the same error can be seen in current master branch.

## Code - Problem

The internal function "loadCheckboxStates" (ln. 80, cookieman.js) is called in the "init" call and resets the group checkboxes accordingly to the state of the current cookie settings. It uses "consentedSelectionsAll" for that, which can not differentiate between a cookie which has all states deselected and the state that no cookie is set at all. Therefore it interprets the lacking of the cookie on the initial call as a user who deselected all (not-disabled) options.

## Possible Solution
The "loadCheckboxStates" function should check at first, if the consent cookie was set at all. (Like in the showOnce method) If not, the checkbox states should not be changed.

**Comment by jonaseberledmind** [comment]
Hi Philipp, thank you for spotting this bug, your report and the solution!
I agree that returning early in `loadCheckboxStates` if no cookie is set yet would solve it.

**Comment by jonaseberledmind** [comment]
Could you check if this fixes it?

**Comment by philippmaurer** [comment]
Yep, the problem is solved :-) Thanks

**Comment by jonaseberledmind** [comment]
@philippmaurer Thank you! I did not plan a new release yet but if you insist we can do it.
