### ISSUE TITLE
JS API endpoint to directly check if a specific trackingobject is allowed

### ISSUE THREAD

**Issue by philippmaurer** [dmind-gmbh/extension-cookieman#87]
# Feature Request

**Is your feature request related to a problem? Please describe.**
If you are coding an action on your website's frontend, that you only want to do if the user accepted it in the cookieman extension, you currently need to check if the corresponding group that trackingobject is in was accepted. Therefore, you always need to know the group that the cookie/request is in when programming it. Changing one cookie from one group to another also requires changes in your website logic.

**Describe the solution you'd like**
I would like to have an API endpoint to which i can provide the name of a tracking object (e.g. name of the cookie) and it would internally find out its corresponding group and return true if that group was accepted, or false if it was not.
If the tracking object is present in multiple groups, it should be possible to specify the endpoint behavior in a TypoScript settings. It should either return true if all corresponding groups were accepted, or it should return true if at least one was accepted.
By default, the more restrictive one should be set.

**Describe alternatives you've considered**
- Instead of creating a new endpoint, it would be a possible solution to provide a trackingobject's name to the "hasConsented" enpoint. This solution though would either require an extra parameter for that endpoint to specify whether or not the name of a group or a trackingobject was provided, or would cause troubles if the name of a trackingobject is also the name of a group.
- I created my own dictionary in which i specify the group for each tracking object, so before i call the API endpoint, i get the group of my trackingobject and check that then. This works fine, but still requires me to change that one place in my code if i should change the group of one of my tracingobjects.

**Comment by jonaseberledmind** [comment]
Hi Philipp, thank you for your request.
That would certainly not be too hard.

Regarding the wording: We use the hierarchie `group` (e.g. marketing) › `trackingObject` (e.g. GoogleAnalytics) › `trackingObjectItem` (e.g. _ga HTML-cookie or a LocalStorage entry or a tracking pixel or...) in https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Public/Js/cookieman.js

I agree that API functions like `hasConsentedTrackingObject()` and `hasConsentedTrackingObjectItem()` would be beneficial.

**Comment by philippmaurer** [comment]
I could create a pull request for that, too. Interested?

**Comment by jonaseberledmind** [comment]
yes, you are welcome to do that :)

**Comment by philippmaurer** [comment]
@jonaseberledmind Pushed a commit on my fork. If you agree with the implentation i would create the documentation and a pull request, otherwise i would appreciate comments 87c0ced37d1e1a679e95daef67f427e63828079a

**Comment by jonaseberledmind** [comment]
Thank you!

After thinking about it I would leave out `hasConsentedTrackingObjectItem()` because it really only makes sense for our configuration structure together with a given trackingObjectKey in which case you would rather use `hasConsentedTrackingObject()` directly.
Let's keep the API strict.
