### ISSUE TITLE
add docu for changing default template via root paths

### ISSUE THREAD

**Issue by medarob** [dmind-gmbh/extension-cookieman#91]
# Feature Request

Maybe it's possible add the following to the documentation if that can be used and there are no drawbacks. In the current documentation there is a "how-to" change or add an existing template section (Create a new theme or adapt an existing one).

I think it's missing the explanation that it's also possible to change the default templates via adpating the root paths, for example add this to your own `setup.typoscript` extension:

```
page {
	1365499 = FLUIDTEMPLATE
	1365499 {
		templateRootPaths {
			150 = EXT:my-ext/Resources/Private/cookieman/Templates/{$plugin.tx_cookieman.settings.theme}/
		}

		partialRootPaths {
			150 = EXT:my-ext/Resources/Private/cookieman/Partials/
		}

		layoutRootPaths {
			150 = EXT:my-ext/Resources/Private/cookieman/Layouts/
		}
	}
}
```

That way, you don't need to add `cookieman-theme.css` and `cookieman-theme.js` to your own theme because the default files in EXT:cookieman are used.

Not sure if there are any disadvantages to this approach? Any recommendations?

**Comment by jonaseberledmind** [comment]
That's a good idea. 
I suggest adding a section "Adapting default themes" in front of https://docs.typo3.org/p/dmind/cookieman/master/en-us/Configuration/Customization/Index.html
